[project]
name = "smon-toolbox"
version = "0.1.0"
description = "PhD Computational Toolbox"
readme = "README.md"
authors = [
    { name = "Simon Ghyselincks", email = "sghyseli@cs.ubc.ca" }
]
requires-python = ">=3.13"
dependencies = [
    "einops>=0.8",
    "numpy>=2.0",
    "scipy>=1.13",
    "torch>=2.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/smon_toolbox"]

[dependency-groups]
dev = ["pytest", "black", "isort"]

[tool.black]
line-length = 108
target-version = ['py313']
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 108
multi_line_output = 3

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
